version : "1.0"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chainskills-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./gameBackend
      dockerfile: Dockerfile
    container_name: chainskills-backend
    ports:
      - "5000:5000"
    restart: unless-stopped        
